---
date: "2018-09-02"
draft: false
title: About
---


Thank you to Orianna for developing the [AllinOne Theme](https://github.com/orianna-zzo/AllinOne)  used for this website. 

The static site is generated by [Hugo](http://gohugo.io) and is deployed on [Netlify](https://www.netlify.com). 



