baseURL                   = "https://tannergildea.com"
builddrafts                = false
languageCode               = "en-us"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 25
Paginate                   = 5

theme = "AllinOne"
title                      = "Tanner Gildea"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
    
  [[menu.main]]
    name                   = "Data Projects"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 
    
  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/headshot_gildea.jpg"               # from static/
  avatar                   = "img/headshot_gildea.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Tanner Gildea"
  description              = ["Former 2020 Democratic primary organizer", "Proud oldest brother of four", "Interested in progressive political opportunities"]           # appears in the site header when set to a non-empty string
  welcome_head             = ""
  welcome_word             = ""

  latestpostscount         = 0                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "gildea.tanner@gmail.com"
  twitter                  = "//twitter.com/wtannergildea" 
  github                   = "//github.com/wtannergildea"
  linkedin                 = "//linkedin.com/in/w-tanner-gildea-ba1314112/"


  
  # analytics
  googleAnalytics          = "UA-144579574-1"
    
    
