---
title: "On Prosecuting Trump"
author: "Tanner Gildea"
date: "2019-06-12"
output: html_document
---

# Threats to Prosecute Trump After His Term are Dangerous

In the wake of Special Counsel Mueller's much-anticipated report on Russian interference into the 2016 election, some Democrats (and lone [Republican Rep. Justin Amash](https://www.washingtonpost.com/powerpost/amash-accuses-barr-of-deliberately-misrepresenting-muellers-report-to-protect-trump/2019/05/28/70e4b3ee-8141-11e9-933d-7501070ee669_story.html?utm_term=.6b4c7a0ec784)) have called for formal impeachment proceedings against President Trump, despite Mueller's surprisingly [inconclusive findings](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=2ahUKEwjQ9_nNvrPjAhVECc0KHT5DCGsQFjAGegQIAhAB&url=https%3A%2F%2Ftime.com%2F5574575%2Fmueller-report-trump-russia-evidence%2F&usg=AOvVaw0DGU2ol_fcspB66qoprhQK). Speaker Nancy Pelosi, wary of the political downside presented by impeaching Trump without ammo from Mueller - not to mention broad bipartisan support - has, for the time being, bucked her fellow caucus members. 

Out on the campaign trail, Democrats vying to challenge Trump in 2020 have faced the same pressure to call for impeachment themselves. [Many have](https://www.businessinsider.com/who-supports-impeachment-major-democrats-2020-candidates-want-impeach-trump-2019-5#sen-elizabeth-warren-of-massachusetts-became-the-first-2020-presidential-candidate-to-come-out-in-favor-of-impeachment-shortly-after-the-release-of-the-mueller-report-5). Where candidates start to differentiate themselves and the conversation becomes more interesting, even dangerous, is when they are asked: what happens after Trump has left office?

In the hypothetical scenario in which Trump is not impeached and is either voted or term-limited out of office, [one candidate said](https://www.npr.org/2019/06/08/730941386/harris-justice-dept-would-have-no-choice-but-to-prosecute-trump-after-presidency) their Department of Justice would "have no choice and that they should" pursue criminal obstruction of justice charges against him. 

I strongly disagree.

If it’s so clear Trump committed crimes in office, it’s up to Congress to impeach and convict - regardless of their will to do so. Barring new information, to call for prosecution by the next administration appears vengeful, jumping the gun, divisive and irresponsible. It’s reminiscent (although substantively different) of Trump’s 2016 [campaign call to prosecute](https://abcnews.go.com/Politics/10-times-trump-called-hillary-clinton-democrats-investigated/story?id=51138506) his political opponent Hillary Clinton. The leaders of other, less democratic countries have operated this way, and it’s not how we should.

Furthermore, saying the DOJ would have “no choice” but to prosecute falls into the longtime trap of denying the existence of [prosecutorial discretion](https://criminal.findlaw.com/criminal-procedure/what-is-prosecutorial-discretion-.html). Just because they have "seen prosecution of cases on much less evidence" does not mean the case is worth prosecuting - especially when Trump will realistically no longer pose the threat of repeating his alleged crimes.

I sympathize with those eager to impeach Trump or pursue charges against him - if he doesn't suffer consequences for his actions, then how can we expect others to be deterred? He's certainly guilty of debasing the office of the Presidency.

Ultimately, however, I want Trump held accountable where it matters most - at the ballot box in 2020. The historical record will punish him enough.
