---
title: "Covid-19 case and vaccination tracker [in progress]"
author: "Tanner Gildea"
date: "2020-12-28"
output: html_document
tags:
  - "healthcare"
  - "NY Times"
  - "Covid-19"
  - "Tanner Gildea"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.width = "120%")
library(tidyverse)
library(rgdal)
library(maptools)
library(mapproj)
library(rgeos)
library(ggplot2)
library(plotly)
library(rjson)
library(ggridges)
library(readr)
library(ggthemes)
library(rvest)
library(httr)


# download and unzip shape files
download.file("https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_state_20m.zip", destfile = "states.zip")
unzip("states.zip") 

# read shapefile
us <- readOGR(dsn = "cb_2018_us_state_20m.shp", layer = "cb_2018_us_state_20m", verbose = FALSE)

# convert it to Albers equal area
us_aea <- spTransform(us, CRS("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"))
us_aea@data$id <- rownames(us_aea@data)

# extract, then rotate, shrink & move alaska (and reset projection)
# need to use state IDs via # https://www.census.gov/geo/reference/ansi_statetables.html
alaska <- us_aea[us_aea$STATEFP=="02",]
alaska <- elide(alaska, rotate=-50)
alaska <- elide(alaska, scale=max(apply(bbox(alaska), 1, diff)) / 2.3)
alaska <- elide(alaska, shift=c(-2100000, -2500000))
proj4string(alaska) <- proj4string(us_aea)

# extract, then rotate & shift hawaii
hawaii <- us_aea[us_aea$STATEFP=="15",]
hawaii <- elide(hawaii, rotate=-35)
hawaii <- elide(hawaii, shift=c(5400000, -1400000))
proj4string(hawaii) <- proj4string(us_aea)

# remove old states and put new ones back in; note the different order
# we're also removing puerto rico in this example but you can move it
# between texas and florida via similar methods to the ones we just used
us_aea <- us_aea[!us_aea$STATEFP %in% c("02", "15", "72"),]
us_reshaped <- rbind(us_aea, alaska, hawaii)

#convert shapefile to geoJSON for plotly/leaflet
geojson_file <- "us_reshaped.json"
#writeOGR(us_reshaped, geojson_file,layer = "geojson", driver = "GeoJSON")
#us_json <- fromJSON(file = "us_reshaped.json")

# use glimpse(us_reshaped@data) to identify opportunities to join shapefile with other data
# looks like STUSPS or NAME columns in us_reshaped are good join keys


##################3
###################
###################
# other NYT data

# state population data 2019
download.file("https://www2.census.gov/programs-surveys/popest/tables/2010-2019/state/totals/nst-est2019-01.xlsx", destfile = "state_pop.xlsx")

state_pop <- readxl::read_xlsx("state_pop.xlsx", skip = 2) %>%
  select('Geographic Area',13) %>%
  rename(pop = 2,
         state = 'Geographic Area') %>%
  mutate(state = str_remove_all(state, '\\.'))

# daily case counts from NYT
daily_states <- read_csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")) %>%
  group_by(state) %>%
  arrange(state)

daily_states <- daily_states %>%
  mutate(yesterday_date = date - 1)

daily_states <- daily_states %>%
  left_join(daily_states, by = c("yesterday_date" = "date", "state" = "state")) %>%
  mutate(new_cases = cases.x - cases.y,
         new_deaths = deaths.x - deaths.y) %>% 
  select(date, state, fips.x, cases.x, deaths.x, new_cases, new_deaths) %>%
  replace(is.na(.),0) %>%
  rename(cases = cases.x,
         deaths = deaths.x,
         fips = fips.x) %>%
  left_join(state_pop, by = c("state" = "state")) %>%
  mutate(perc_pop_covid = round(100*cases / pop,3),
         perc_pop_death = round(100*deaths / pop,3),
         new_cases_prop = round(100*new_cases / pop,3),
         new_deaths_prop = round(100*new_deaths / pop,3)) %>%
  filter(date > '2020-03-01') %>%
  filter(!state %in% c("Northern Mariana Islands","Guam","Virgin Islands"))


####
# get state region data
state_regions <- read_csv(url("https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv")) %>%
  select(State,Region)

```
Last updated: `r format(as.Date(Sys.Date(),"%Y-%m-%d"), "%B %d, %Y")`  

  

## Ridge plot  

```{r ridgeplot cases, echo=FALSE, fig.height = 20, fig.align='center'}
## ridge plot of daily new cases per state             
daily_states %>% 
  mutate(cum_cases = max(cases)) %>%
  arrange(desc(cum_cases)) %>%
  ungroup() %>%
  mutate(state = fct_reorder(state, cum_cases, max)) %>%
  
ggplot(aes(x = date, 
           y = state, 
           ordered = TRUE, 
           height = new_cases,
           fill = state)) +
  
  geom_density_ridges2(stat = "identity", 
                      alpha = .6, 
                      scale = 10,
                      size = .2) +
  
  theme_ridges() +
  
  labs(x = NULL, 
       y = NULL,
       title = "New Daily Cases of Covid-19",
       caption = "Data from The New York Times and U.S. Census Bureau.") +
  
  scale_fill_cyclical(values = c("red","orange","yellow")) +
  
  theme(axis.text.y = element_text(size=12),
        axis.text.x = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        text=element_text(family="Georgia"),
        plot.title = element_text(size=22, face = "bold", hjust = 0),
        plot.margin = margin(2,6,1,1,"mm"),
        plot.caption = element_text(face = "italic")) +
  
  coord_fixed(ratio = 20)
  
  
```

## Proportional ridge plot


```{r ridgeplot proportion cases, echo=FALSE, fig.height = 18.5, fig.align='center'}
## ridge plot of daily new cases per state             
daily_states %>%
  mutate(prop_rank = sum(new_cases_prop)) %>%
  arrange(desc(prop_rank)) %>%
  ungroup() %>%
  mutate(state = fct_reorder(state, prop_rank, max)) %>%

ggplot(aes(x = date, 
           y = factor(state, levels = rev(unique(state))), 
           ordered = TRUE, 
           height = new_cases_prop,
           fill = state)) +
  
  geom_density_ridges2(stat = "identity", 
                      alpha = .6, 
                      scale = 6,
                      size = .2) +
  
  theme_ridges() +
  
  labs(x = NULL, 
       y = NULL,
       title = "New Daily Cases of Covid-19",
       subtitle = "as proportion of each state's population",
       caption = "Data from The New York Times and U.S. Census Bureau.") +
  
  scale_fill_cyclical(values = c("purple","blue","dark blue")) +
  
  theme(axis.text.y = element_text(size=12),
        axis.text.x = element_text(face = "bold"),
        panel.grid.major.x = element_blank(),
        text=element_text(family="Georgia"),
        plot.title = element_text(size=22, face = "bold"),
        plot.margin = margin(0,6,0,1,"mm"),
        plot.caption = element_text(face = "italic")) +
  
  coord_fixed(ratio = 20)
  
```

```{r mask wearing, echo = FALSE, include=FALSE}
# library(covidcast)
# 
# cc_data <- suppressMessages(
#   covidcast_signal(data_source = "fb-survey", signal = "smoothed_wearing_mask",
#                    start_day = "2020-04-06", end_day = "2020-12-18",
#                    geo_type = "state"))
# 
# st_crosswalk <- tibble(state = state.name) %>%
#   bind_cols(tibble(abb = state.abb)) %>% 
#   bind_rows(tibble(state = "District of Columbia", abb = "DC")) %>%
#   mutate(abb = str_to_lower(abb))
# 
# cc_data <- left_join(cc_data, st_crosswalk, by = c("geo_value" = "abb")) %>%
#   group_by(state) %>%
#   summarize(mean_mask_perc = round(mean(value),0))
#   
# prop_deaths <- daily_states %>%
#   summarize(cum_deaths = max(deaths),
#             pop = pop)
# 
# mask <- cc_data %>%
#   left_join(prop_deaths, by = c("state" = "state")) %>%
#   distinct() %>%
#   mutate(prop_deaths = round(100*cum_deaths/pop,3)) 
#   
# ggplot(mask,aes(x=prop_deaths, y = mean_mask_perc)) +
#   geom_point() +
#   geom_smooth(method=lm, se= FALSE)
#  scale_y_log10()
```

## Segment Chart
```{r bar charts, echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', fig.height= 14, out.width= "100%"}
covid_summary <- daily_states %>%
  select(state, fips, cases, deaths, perc_pop_covid, perc_pop_death, pop) %>%
  summarize(total_cases = max(cases),
            total_deaths = max(deaths),
            perc_pop_covid = max(perc_pop_covid)/100,
            perc_pop_death = max(perc_pop_death)/100,
            pop = max(pop)) %>%
  left_join(state_regions, by = c("state" = "State")) %>%
  filter(!is.na(Region)) %>%
  arrange(perc_pop_covid) %>%
  mutate(state = factor(state, levels = state))

ggplotly(ggplot(covid_summary, aes(x = state, 
                                   y = perc_pop_covid, 
                                   color = Region, 
                                   # for plotly display box later on
                                   text = paste0("<b>State: </b>", state,"<br>",
                                                 "<b>% of pop. diagnosed: </b>", round(perc_pop_covid*100,2),"% <br>",
                                                 "<b>total # of cases: </b>", total_cases))) +
  
  geom_segment(aes(xend = state, yend=0)) +
  
  geom_point(size = 4, color = "black") +
  
  scale_y_continuous(labels= scales::percent) +
  
  coord_flip() +
  
  labs(x = NULL,
       y = NULL,
       title = "Percent of state population diagnosed with Covid to date",
       caption = "Data from The New York Times and U.S. Census Bureau.") +
  
  facet_wrap(~Region, ncol = 1, scales = "free_y") +
  
  theme_tufte() +
  
  theme(axis.text.y = element_text(size=12),
        axis.text.x = element_text(face = "bold"),
        text=element_text(family="Georgia"),
        plot.caption = element_text(face = "italic"),
        plot.title = element_text(size=16, face = "bold"),
        legend.position = "none",
        strip.text.x = element_text(size = 14, face = "bold"),
        panel.grid.major.x = element_line(colour = "grey", size = 0.5)),

  tooltip = "text") %>%
  
  #ggplotly options
  plotly::config(displayModeBar = FALSE) %>%
  layout(hoverlabel = list(bgcolor = "white",
                           font = list(family = "Georgia")))
```

## Vax Maps
assume herd immunity at [70% protection](https://www.mayoclinic.org/diseases-conditions/coronavirus/in-depth/herd-immunity-and-coronavirus/art-20486808)
```{r web scrape vax, echo = FALSE, message=FALSE, warning=FALSE,fig.align='center'}
# scrape vax data from NY Times website https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html
vax_html_raw <- content(GET('https://www.nytimes.com/interactive/2020/us/covid-19-vaccine-doses.html'))

# turn into manageable table
vax <- vax_html_raw %>%
  html_node('table') %>%
  html_table() %>%
  rename(state = 1) %>%
  rename(doses_allocated = `Doses allocated`,
         doses_received = `Doses confirmed received`,
         shots_given = `Shots given`) %>%
 mutate(doses_allocated = parse_number(doses_allocated),
        doses_received = parse_number(doses_received),
        shots_given = parse_number(shots_given))

# join with covid_summary table and add more summary stats
master_summary <- covid_summary %>%
  left_join(vax, by = "state") %>%
  mutate(perc_vax = shots_given/pop) %>%
  mutate(perc_protection = perc_vax + perc_pop_covid) %>%
  mutate(perc_herd_immunity = perc_protection/0.7) %>%
  mutate(perc_vax_given = shots_given/doses_received)

# import shapefile and fortify for ggplot (source: https://www.marmoe.xyz/2018/09/04/shapefiles-in-r-with-ggplot2-rgdal/)
map_shp <- broom::tidy(us_reshaped)
us_reshaped$id <- row.names(us_reshaped)
map_shp <- left_join(map_shp, us_reshaped@data)

# add covid and vax info
map_data <- left_join(map_shp, master_summary, by = c("NAME" = "state"))

# make map
ggplot(map_data, aes(x = long, 
                     y = lat, 
                     group = group, 
                     fill = perc_vax)) +
  
  geom_polygon(color = "white",
               size = .2) +
  
  theme_map() +
  
  labs(x = NULL, 
       y = NULL,
       title = "Percent of U.S.population vaccinated against Covid-19",
       subtitle = NULL,
       caption = "Data from The New York Times and U.S. Census Bureau.",
       fill = NULL) +
  
  scale_fill_gradient(low = "grey", high = "light blue", labels = scales::percent) +
  
  theme_map() +

  theme(legend.position = "right",
        plot.caption = element_text(face = "italic"),
        plot.title = element_text(size=16, face = "bold"),
        text=element_text(family="Georgia"))

```

```{r herd immunity map, echo = FALSE, message=FALSE, warning=FALSE,fig.align='center'}
# make map
ggplot(map_data, aes(x = long, 
                     y = lat, 
                     group = group, 
                     fill = perc_herd_immunity)) +
  
  geom_polygon(color = "white",
               size = .2) +
  
  theme_map() +
  
  labs(x = NULL, 
       y = NULL,
       title = "Percent of the way to 70% herd immunity threshold",
       subtitle = paste0("Estimated from confirmed vaccinations and infections. \nAssume lag in reported vaccinations,and significant undercount in confirmed infections."),
       caption = "Data from The New York Times; U.S. Census Bureau; U.S. Department of Health and Human Services (Pfizer and Moderna doses allocated); state surveys and announcements (doses confirmed received and shots given).",
       fill = NULL) +
  
  scale_fill_gradient(low = "grey", high = "PaleGreen", labels = scales::percent) +
  
  theme_map() +
  
  theme(legend.position = "right",
        plot.caption = element_text(face = "italic"),
        plot.title = element_text(size=16, face = "bold"),
        text=element_text(family="Georgia"))

```


```{r bar plot distribution, echo = FALSE, message=FALSE, warning=FALSE,fig.align='center', fig.height= 10}
# compare vaccine allocated, distributed, and given across states
bar_stats <- master_summary %>%
  select(state, doses_allocated, doses_received, shots_given) %>%
  mutate(state = factor(state, levels = state)) %>%
  pivot_longer(!state, "metric", "value") 
  
bar_stats <- master_summary %>%
  select(state,Region, perc_vax_given) %>%
  right_join(bar_stats, by = "state") %>%
  arrange(value) %>%
  mutate(state = factor(state, levels = unique(state)))


ggplot(bar_stats, aes(x= state, y = value, fill = metric)) +
  
  geom_col(position = "dodge") +
  
  facet_wrap(~Region, ncol = 2, scales = "free_y") +
  
  labs(x = NULL,
       y = NULL,
       title = "Vaccine allocation and distribution",
       caption = "Data from The New York Times; U.S. Department of Health and Human Services (Pfizer and Moderna doses allocated); state surveys and announcements (doses confirmed received and shots given).") +
  
  coord_flip() +
  
  theme_tufte() +
  
  theme(axis.text.y = element_text(size=12),
        axis.text.x = element_text(face = "bold"),
        text=element_text(family="Georgia"),
        plot.caption = element_text(face = "italic"),
        plot.title = element_text(size=16, face = "bold"),
        legend.position = "bottom",
        strip.text.x = element_text(size = 14, face = "bold"),
        panel.grid.major.x = element_line(colour = "grey", size = 0.5))



```
