---
title: The Tweets of the 2020 Democratic Primary
author: Tanner Gildea
date: '2019-07-10'
tags:
  - '2020'
  - "Tanner Gildea"
output: html_document
---

A record number of Democrats are seeking their party's nomination for the Presidency in 2020. Presumptive front-runners Joe Biden and Bernie Sanders aren't scaring away the competition: the field includes former and sitting U.S. senators, representatives, governors, a mayor, cabinet secretaries, an author, and a tech executive.


The success of any presidential campaign hinges on the candidate's ability to connect with voters on the ground, especially in the early primary and caucus states of Iowa, New Hampshire, South Carolina, and Nevada.


As proven by the current President, however, campaigns are also waged online - especially on Twitter. According, the 2020 Democratic primary candidates have all taken to the platform to spread their message.


But how has each candidate used Twitter? How frequently do they tweet? How are their tweets received? What language do they use, what's the tone of their writing, and what issues are they talking about most?


Using Twitter's API, I tried to answer these questions. For my analysis, I picked twelve of the most popular candidates, both in terms of polling and fundraising. The results of my analysis are published on an [interactive Shiny dashboard available here.](https://wtannergildea.shinyapps.io/2020-Dems_2/)


